# Generated by Django 4.1.1 on 2022-10-29 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('politique', 'politique'), ('sport', 'sport'), ('social', 'social'), ('Autre', 'Autre')], default='social', max_length=25)),
                ('post_titre', models.CharField(blank=True, max_length=25, null=True)),
                ('post_img', models.CharField(blank=True, max_length=25, null=True)),
                ('post_url', models.CharField(max_length=25)),
                ('texte', models.TextField(unique=True)),
                ('haineux', models.IntegerField(default=0)),
                ('offensif', models.IntegerField(default=0)),
                ('non_offensif', models.IntegerField(default=0)),
                ('vote_final', models.CharField(default='', max_length=25)),
                ('file_name', models.CharField(blank=True, max_length=25, null=True)),
                ('publied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
