# Generated by Django 4.1.1 on 2022-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
