# Generated by Django 4.1.1 on 2022-09-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComments', '0002_comment_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
