# Generated by Django 4.1.1 on 2022-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComments', '0003_alter_comment_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='texte',
            field=models.TextField(unique=True),
        ),
    ]
