# Generated by Django 4.1.1 on 2022-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComments', '0004_alter_comment_texte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='temp_haineux',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='temp_non_offensif',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='temp_offensif',
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_final',
            field=models.CharField(default='', max_length=25),
        ),
    ]
