# Generated by Django 4.1.1 on 2022-10-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temporaire',
        ),
    ]
