# Generated by Django 4.1.1 on 2022-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComments', '0001_initial'),
        ('AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked',
            field=models.ManyToManyField(related_name='checked_comments', to='AppComments.comment'),
        ),
    ]
