# Generated by Django 4.1.1 on 2022-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0002_user_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
